2018-06-12 07:34:10,899 ERROR waitress Exception when serving /
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\waitress\channel.py", line 338, in service
    task.service()
  File "C:\Python\Python36\lib\site-packages\waitress\task.py", line 169, in service
    self.execute()
  File "C:\Python\Python36\lib\site-packages\waitress\task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "C:\Python\Python36\lib\site-packages\falcon\api.py", line 244, in __call__
    responder(req, resp, **params)
  File "G:\Repos\Rexroth\jsonrpc_server\falcon_api_pg.py", line 95, in on_post
    resp.json = {"jsonrpc":"2","method":"post", data:data}
TypeError: unhashable type: 'dict'
2018-06-12 07:34:50,127 DEBUG api {'dsn': 'dbname=mabo user=mabo password=mabo2018 port=6432', 'dbname': 'mabo', 'user': 'mabo', 'password': 'mabo2018'}
2018-06-12 07:34:50,143 INFO main start
2018-06-12 07:35:28,085 DEBUG api post
2018-06-12 07:35:35,510 DEBUG api {'key1': 'value1', 'key2': 'value2'}
2018-06-12 07:35:35,516 DEBUG api put
2018-06-12 07:35:50,575 DEBUG api post
2018-06-12 07:35:50,576 DEBUG api {'key1': 'value1', 'key2': 'value2'}
2018-06-12 07:35:50,580 DEBUG api put
2018-06-12 07:36:10,446 DEBUG api post
2018-06-12 07:36:10,447 DEBUG api {'key1': 'value1', 'key2': 'value2'}
2018-06-12 07:36:10,453 DEBUG api put
